### ISSUE TITLE
Npn Slider not accepting 0 for min

### ISSUE THREAD

**Issue by DokurOmkar** [npnm/NpnSlider#10]
Hi Nupin,

When I use [min]=0, the slider is not working at the first load. 

Here is the example I am using:
`  <npn-slider 
                    [min]="0" 
                    [max]="24" 
                    disabled="{{!filtersEnabled}}"
                    [showStepIndicator]="true" 
                    (onChange)="onHourChangeEnd($event)">
                </npn-slider>`

Please advise.

**Comment by npnm** [comment]
Thank you for reporting this issue. I fixed it.
Please take latest version of npn-slider [v1.3.2](https://www.npmjs.com/package/npn-slider)

cheers!
