### ISSUE TITLE
angular 7 upgrade

### ISSUE THREAD

**Issue by chinnarao** [npnm/NpnSlider#3]
![image](https://user-images.githubusercontent.com/3664053/48232735-780c2a80-e367-11e8-803e-64cb7c48e15c.png)

**Comment by shadowalkersb** [comment]
Hi!
tnx for your awesome slider!
I had this slider on my app and it worked perfectly.
but since I upgraded to angular 7 it's not :\
what can I do to fix the problem?

**Comment by npnm** [comment]
Thank you @chinnarao and @shadowalkersb for reporting the issue. I just made a patch release with support for angular 7. 
Please use the new version of **npn-slider v1.2.1**.

Please keep report any issues you face. Thank you
