### ISSUE TITLE
Use of Browser Module throw Error

### ISSUE THREAD

**Issue by MehtaAr25** [npnm/NpnSlider#4]
The Slider uses Browser Module instead of Common Module and thus throws below error

Error: Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead. BrowserModule@http://localhost:4200/vendor.js:67606:28 _createClass@http://localhost:4200/vendor.js:47231:28 _createProviderInstance@http://localhost:4200/vendor.js:47203:38 initNgModule@http://localhost:4200/vendor.js:47136:55 NgModuleRef_@http://localhost:4200/vendor.js:47862:21 createNgModuleRef@http://localhost:4200/vendor.js:47851:28 http://localhost:4200/vendor.js:71474:40 _next@http://localhost:4200/vendor.js:126370:39 next@http://localhost:4200/vendor.js:121084:23 http://localhost:4200/vendor.js:131858:32 onInvoke@http://localhost:4200/vendor.js:42637:39 run@http://localhost:4200/polyfills.js:2472:49 http://localhost:4200/polyfills.js:3211:37 onInvokeTask@http://localhost:4200/vendor.js:42628:43 runTask@http://localhost:4200/polyfills.js:2517:57 drainMicroTaskQueue@http://localhost:4200/polyfills.js:2923:42 promiseReactionJob@[native code]

**Comment by npnm** [comment]
Thank you reporting this issue. 
It has been fixed in [npn-slider v1.3.0](https://github.com/npnm/NpnSlider/releases/tag/v1.3.0)
Please take latest version of npn-slider

cheers!
