### ISSUE TITLE
 Error: Hammer.js is not loaded, can not bind panend event

### ISSUE THREAD

**Issue by NambiRcggs** [npnm/NpnSlider#7]
What shall i import and where, to get rid of this error?

**Comment by npnm** [comment]
Could you please tell me version of angular and npn-slider you are using now?
and when you are seeing this error? at run time or compile time?

**Comment by NambiRcggs** [comment]
Thax guys.I cleared the issue by importing hammer to app module

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by npnm** [comment]
Good to hear that you resolved the issue.

But seems like you have been forced to include hammerjs in your project for npn-slider.

NpnSlider is using hammerjs to support touch events. If touch events are not required, then there is no need of hammerjs

So I would recommend you to try using NpnSlider without hammerjs if you really don’t want to support mobile users. 

If you see issues, please let me know

Thank you
